name: Scrape

on:
  schedule:
    - cron: "0 */20 * * *"
  workflow_dispatch:

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Airbnb Scraper
        run: python airbnb.py

      - name: Run Ventura RV Connection
        run: python venturarvconnection.py
